# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source :gemcutter


gem "rdoc", ">=0", :group => [:development, :test]
gem "hoe-gemspec", ">=0", :group => [:development, :test]
gem "hoe-bundler", ">=0", :group => [:development, :test]
gem "activerecord", "=2.3.2", :group => [:development, :test]
gem "sqlite3", ">=0", :group => [:development, :test]
gem "hoe", "~>2.12", :group => [:development, :test]

# vim: syntax=ruby
